[build]
  command = "npm ci && npm run build"
  publish = "dist"

[dev]
  command = "npm run dev"
  port = 5173  # Vite's default port
  targetPort = 5173

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18.0.0"  # Specific version to ensure consistency
  NPM_FLAGS = "--legacy-peer-deps"  # Helps with dependency resolution

[build]
  command = "rm -rf node_modules && rm -f package-lock.json && npm install && npm run build"
  publish = "dist"

[context.production.environment]
  NODE_VERSION = "18.0.0"
  NPM_FLAGS = "--legacy-peer-deps"
